import React from 'react';
import { useState } from 'react';
import { motion } from 'framer-motion';
import './index.css';

export default function App() {
  const [lang, setLang] = useState('en');

  const translations = {
    en: {
      title: 'Sniff 🐶 – The AI Dog Sniffing Out Airdrops and Injustice',
      subtitle: 'Sniff is your AI-powered watchdog – hunting valuable airdrops and challenging real-world cruelty.',
      cta: '🚀 Explore the Sniff Mission',
      footer: 'Built by humans. Powered by dogs. Driven by justice. © 2025 Sniff Protocol',
      toggle: '日本語へ',
      requirements: 'Requirements',
      why: 'Why Sniff?',
      whyText: `Sniff isn’t just another crypto analytics tool—it’s your unfair advantage in the airdrop race.

      In Web3, information overload is constant. Every day brings a new project, a new promise, a new buzz. But most of them are noise. Scammy Discord servers, fake Twitter hype, paid influencers—all manipulating attention. By the time the masses catch on, the real opportunities are long gone.
      
      Sniff is different. It’s your personal watchdog—a decentralized AI system trained to sniff out airdrops before they surface. We deploy multiple AI agents, each with deep domain expertise:
      - NLP models read the tone of announcements and developer updates
      - Smart contract evaluators flag honeypots and flawed tokenomics
      - Social signal agents detect inorganic virality and bot-driven campaigns
      - Memory agents remember past scams, rug pulls, and pump patterns
      
      What you get is not a list of projects. You get intelligence. Curated, explainable airdrop leads scored and filtered to match your risk profile and preferences. It’s discovery without distraction. Efficiency without compromise.
      
      Sniff isn’t chasing influencers or alpha groups—it’s building a machine that finds what others miss. We don’t wait for hype to validate a project. We analyze, score, and sniff before the crowd even hears a bark.
      
      But there’s more. Every sniff you follow also fights injustice. A fixed percentage of the protocol’s revenue goes directly to real-world animal rescue programs. In regions where dogs are abused, abandoned, or euthanized in secret, Sniff brings visibility, funding, and action. We partner with transparent organizations in Japan, the U.S., Southeast Asia, and beyond to create systemic change.
      
      In a world where profit usually comes at the expense of ethics, Sniff proves you can win both ways. Sniff is the first airdrop protocol that’s not just optimized for financial alpha—but for moral alpha too.
      
      It’s time to replace noise with trust. Replace hype with detection. Replace apathy with impact.
      
      Built by humans. Powered by dogs. Trained to sniff opportunity—and injustice.
      `,
      how: 'How Sniff Score Works',
      howText: `The Sniff Score is not just a number. It’s a dynamic, explainable signal generated by a decentralized ensemble of AI agents—each trained in a specific analytical domain—to detect, evaluate, and prioritize airdrop-worthy Web3 projects before the crowd.

Sniff’s architecture is modeled after multi-agent systems used in swarm robotics and adversarial inference environments. Each agent operates independently with its own model, data set, and evaluation heuristics. Their insights are then federated via a trust-weighted voting system, producing a final Sniff Score.

■ NLP Agents (Natural Language Processing)
These agents process whitepapers, dev updates, social media posts, and community messages. They assess semantic tone, rhetorical consistency, presence of evasive or promotional language, and similarity to historical scam signatures. They detect red flags like vague roadmaps, excessive future promises, or sudden pivot language.

■ Smart Contract Evaluators
Sniff scans token contracts for structural and behavioral risks: developer wallet concentration, mint/burn functions, ownership transfer logic, honeypot conditions, and time-locked functions. It incorporates static analysis tools like Slither and Mythril, combined with Sniff’s proprietary “Ethical Function Score” (EFS), to measure on-chain integrity.

■ Social Signal Detectors
These agents analyze account age distribution, engagement velocity, hashtag dynamics, influencer overlap, and known bot cluster traces. Using Sniff’s “Pattern Injection Score,” they assess how closely a project’s growth mirrors prior inorganic campaigns—measuring not popularity, but authenticity.

■ Memory Agents
Sniff’s memory subsystem records every past evaluation, tracking the long-term accuracy and volatility of each agent. These histories feed into Dynamic Agent Weighting—an adaptive feedback loop that reduces reliance on underperforming signals and boosts agents with proven precision.

All agents vote on a normalized score between 0–10, with weights adjusted via temporal trust coefficients. The final Sniff Score isn’t static—it reflects continuous updates from real-time data, agent performance, and evolving threat models.

Sniff doesn’t just tell you “what’s hot”—it explains why. It gives you actionable intelligence, not just alerts. Every score is backed by transparent, component-wise rationales that experienced traders and researchers can audit.

This isn’t sentiment analysis. It’s infrastructure-grade AI vigilance—built to scale, built to detect, built to be trusted.

Sniff Score: because in Web3, trust isn't given. It's sniffed out.`,
      utility: 'What $SNIFF Token Does',
      utilityList: [
        "Unlocks personalized airdrop dashboards, real-time cross-chain sniff alerts, and scoring insights powered by decentralized multi-agent AI.",
        "No-code interface to train your own custom AI agent—tailored for specific domains (DeFi, Memecoin, NFT) or scam-immune behavior patterns.",
        "Vote on sniff target priorities, agent upgrades, funding for dog rescue partners, and protocol ethics via SniffDAO.",
        "Your $SNIFF activity affects your SniffRank, which adjusts UI personalization strength, alpha access, and leaderboard placement.",
        "Earn NFT badges, agent beta access, and participation incentives for usage, feedback, and ethical contribution.",
        "A portion of fees is programmatically routed to trusted global dog protection NGOs—fully transparent and auditable on-chain."
      ],      
      giveBack: 'Give Back to Real Dogs',
      giveBackText: `Sniff isn’t just a tool for sniffing airdrops—it’s an instrument of change in the real world. A portion of every $SNIFF transaction directly supports animal welfare through verified dog rescue and no-kill shelters. 

Every year, millions of dogs worldwide face neglect, abuse, and abandonment. According to recent statistics, an estimated 3.3 million dogs enter U.S. shelters alone, with over 1.5 million euthanized due to overcrowding and lack of resources. In Japan, over 50,000 dogs are abandoned annually, and an alarming number of them are subjected to the horrors of puppy mills, where they face abuse and malnutrition.

Sniff partners with trusted organizations across the globe, including rescues like the Humane Society, to directly address issues like overbreeding, abandonment, puppy mills, and the inhumane dog meat trade still prevalent in certain parts of the world. By using $SNIFF, you aren’t just discovering high-value Web3 projects—you’re contributing to a better world for dogs who need it the most. 

Through the Sniff Protocol, we create a direct impact by ensuring that a portion of every token transaction goes towards animal rescue efforts. Whether it’s funding spay/neuter programs, supporting disaster response teams, or lobbying for stricter animal welfare laws, Sniff allows you to contribute while you explore and profit from Web3. Your participation brings both financial and moral reward, creating a legacy of ethical wealth-building in the blockchain space.

The more $SNIFF you use, the more impact you create. Every transaction, every vote, and every dollar spent is an investment in a better future for dogs in need. With Sniff, you can actively fight the injustices of the world while enjoying the benefits of decentralized finance—and know that your actions are creating real-world change, one sniff at a time.`,
      roadmap: 'Roadmap',
      tech: 'Technical Foundations',
      techText: `Sniff is powered by a real-time, decentralized multi-agent AI architecture. Each airdrop is independently analyzed by specialized AI agents—large language models (LLMs) for semantic analysis, on-chain graph analytics engines for token behavior, anomaly detection models for social metrics, and reputation-based memory subsystems. These agents use federated voting with weighted trust scores to generate a robust, interpretable Sniff Score.

Our AI stack runs on serverless edge infrastructure, optimizing for latency and verifiability. Developers can plug in new agents, deploy local fine-tuned models, or access aggregated scoring through our open API. The system is designed for transparency, auditability, and long-term adaptability to adversarial crypto dynamics.`,
      value: 'Why It Matters',
      valueText: `Crypto moves fast. Scams move faster. New users and even seasoned holders often fall prey to hyped projects with no substance. Sniff is your intelligent guard dog—cutting through the noise, surfacing ethical projects, and redistributing value to where it matters: real-world impact and justice.

$SNIFF is more than just a meme token. It's a utility layer for discovery, decision-making, and decentralized enforcement of ethics in Web3.`,
roadmapItems: [
  "Q2 2025: Launch Sniff Score MVP and initiate first real-world donations",
  "Q3 2025: Integrate public Sniff dashboards, NFT badge system, and DAO-based project voting",
  "Q4 2025: Release Sniff API, support multichain sniffing, and beta launch of RescueChain (fund distribution layer)",
  "Q1 2026: Alpha release of SniffNet — create/train custom AI sniff agents with visualized behavior",
  "Q2 2026: Launch SniffCare — wearable-integrated dog emotion and preference interpreter",
  "Q4 2026: Publish the SniffConstitution — global ethical framework for canine welfare",
  "Q1 2027: Begin SniffNation beta — decentralized canine citizenship and incentive economy",
  "Late 2027+: Expand global infrastructure toward autonomous AI-sniffed dog-rights protocol",
  "Future: Every dog is recognized as a sovereign being with digital dignity and agency"
],
recentSniffs: 'Recent Sniffs / Service Highlights',
demoSniffs: [
  {
    name: 'Supporting Local Rescue Organizations',
    type: 'Community Impact',
    requirements: 'Partnerships with local dog rescue groups and shelters.',
    description: 'Sniff is working directly with small, local organizations to support dog rescue missions. These partnerships help ensure that a portion of every $SNIFF token transaction goes towards real-life animal welfare, supporting shelters that are often underfunded.'
  },
  {
    name: 'Ongoing Donations for Dog Welfare',
    type: 'Animal Welfare',
    requirements: 'Contributions made to no-kill shelters and dog rehabilitation centers.',
    description: 'We have made initial donations to several no-kill shelters and dog rehabilitation programs. These ongoing efforts aim to provide rescue dogs with medical treatment and safe living spaces while they await adoption.'
  },
  {
    name: 'Volunteer and Rescue Support Activities',
    type: 'Volunteer Work',
    requirements: 'Participation in volunteer initiatives to help rescued dogs.',
    description: 'Sniff is also supporting volunteer programs that offer training for rescued dogs, helping them become more adoptable. These programs provide educational materials and resources for new dog owners, ensuring that rescued dogs have a loving home.'
  }
]


    },
    ja: {
      title: 'Sniff 🐶 – エアドロと不正を嗅ぎ分けるAI犬',
      subtitle: 'SniffはAIで動く番犬です。価値あるエアドロップと、世界の不条理を嗅ぎつけます。',
      cta: '🚀 Sniffの使命を知る',
      footer: '人が作り、犬が嗅ぎ、正義が動く。© 2025 Sniff Protocol',
      toggle: 'English',
      requirements: '参加条件',
      why: 'なぜSniffなのか？',
      whyText: `Sniffは、ただの仮想通貨ツールではありません。エアドロップ競争を勝ち抜くために設計された、AIによる「先読み型の嗅覚システム」です。

今のWeb3は、毎日のようにプロジェクトが乱立し、次々とエアドロップ情報が流れてきます。しかし、それらの多くは“罠”です。Discordの招待リンク、謎のXキャンペーン、バイラル狙いの偽アカウント、そして資金を奪い逃げるラグプル。そんな世界で、本当に価値あるプロジェクトを、どうやって見抜くのか？

Sniffの答えは明確です。「犬のように、匂いで嗅ぎ分けろ。」

Sniffは、複数のAIエージェントによって構成されています。
・言語処理AIは、開発者の投稿やホワイトペーパーのトーンを解析
・スマートコントラクトアナライザーは、不正な挙動やトークン設計の矛盾を検出
・SNS解析エンジンは、ボット拡散や偽装バズをリアルタイムで監視
・記憶エージェントは、過去の詐欺・成功例を学習し、パターンマッチングで警告を発信

Sniffが提供するのは「リスト」ではなく「洞察」です。単なる情報ではなく、AIによって“本当に可能性があるエアドロップ”だけを、リスク別・テーマ別に整理して通知。あなたは判断だけに集中すればいい。ノイズも、作業も、フィルターも不要です。

Sniffは、誰かの発信やアルファグループに依存しません。Sniffは、誰よりも早く気づき、独自のロジックで“まだ誰も吠えていないチャンス”を発掘します。

さらにSniffの報酬モデルには、「現実世界での正義」が組み込まれています。プロトコルが得た収益の一部は、世界中の保護犬・殺処分ゼロ活動・災害救助・繁殖場問題への対策費として寄付されます。日本、アジア、欧米…地域ごとの団体と連携し、AIとWeb3の力で動物福祉の構造を変えていきます。

Sniffは、儲けと倫理を両立させた世界初のAIプロトコルです。
嗅ぎ当てるのは、チャンスだけではない。不正も、沈黙も、無関心さえも、Sniffは嗅ぎつける。

Web3は、嗅覚が試される時代に入りました。
Sniff——それは、吠える前に気づく、新しい正義の形です。`,

      how: 'Sniffスコアの仕組み',
      howText: `Sniffスコアは、単なる数値ではありません。これは、複数の専門AIエージェントが協調して生成する「動的かつ説明可能な信号」です。各エージェントは独自の専門領域で訓練されており、他の誰よりも早く、価値あるエアドロップ候補を特定・評価・優先順位付けするために機能します。

      Sniffのアーキテクチャは、群ロボティクスや敵対的推論環境で用いられるマルチエージェントシステムに着想を得ています。各エージェントは独自のモデル、データセット、評価アルゴリズムを持ち、独立して分析を行います。最終的なスコアは、信頼加重型のフェデレート投票によって統合されます。
      
      ■ NLPエージェント（自然言語処理）
      ホワイトペーパー、開発者のアップデート、SNS投稿、コミュニティメッセージなどを解析し、文脈のトーン、論理的一貫性、曖昧な表現や誇張的プロモーションの有無を評価します。また、過去の詐欺プロジェクトと類似する言語パターンも検出します。
      
      ■ スマートコントラクト評価エージェント
      開発者ウォレットの集中度、ミント/バーン機能、所有権移譲ロジック、ハニーポット構造、時間制限付き操作などを解析します。SlitherやMythrilなどの静的解析ツールに加え、Sniff独自の「倫理機能スコア（EFS）」によって、コードの健全性と透明性を総合評価します。
      
      ■ ソーシャルシグナル検出エージェント
      アカウントの年齢分布、エンゲージメント速度、ハッシュタグの拡散構造、インフルエンサーとの重複、既知のBotクラスタとの一致などを分析します。Sniff独自の「パターン注入スコア（Pattern Injection Score）」により、成長が本物か捏造かを見極めます。
      
      ■ メモリーエージェント
      各エージェントの過去の評価結果と実際のプロジェクト成果を記録し、長期的な精度・予測の安定性を学習します。この履歴は「動的エージェント重み付け（Dynamic Agent Weighting）」に反映され、信頼性の高いエージェントがより強く評価に寄与するよう適応します。
      
      すべてのエージェントは 0〜10 の正規化スコアに基づいて投票し、時系列的な信頼係数で重み付けされます。Sniffスコアは静的なものではなく、リアルタイムのデータ、モデル性能、脅威モデルの進化に応じて常に更新されます。
      
      Sniffは「何が流行っているか」を伝えるだけではありません。「なぜそう判断したか」まで説明します。出力されるスコアは、熟練トレーダーやリサーチャーが監査可能な、構成要素ごとの根拠を備えています。
      
      これは単なるセンチメント分析ではありません。これはインフラグレードのAI監視レイヤーです。スケール可能で、欺瞞に強く、信頼されるべき仕組み。
      
      Sniffスコア──Web3では信頼は与えられるものではない。嗅ぎ当てるものだ。`,
      
      utility: '$SNIFFトークンの機能',
      utilityList: [
        "パーソナライズされたエアドロップダッシュボード、クロスチェーン通知、AIスコアリング機能にアクセス可能。",
        "ノーコードで自分だけのAIスニファーを育成。DeFiやミームコイン特化型、詐欺耐性型など好みに最適化可能。",
        "Sniff対象の優先設定、エージェント改良、動物保護支援金の配分、倫理基準の更新などに投票可能。",
        "$SNIFFの使用行動がSniffRankに反映され、UIパーソナライズや早期機能アクセス、ランキングに影響。",
        "NFTバッジ、エージェントβアクセス、インセンティブ配布など、実際の活動に応じて報酬を獲得。",
        "収益の一部がスマートコントラクト経由で保護犬団体へ自動配分。全トランザクションは透明に記録。"
      ],
      giveBack: '犬たちへの還元',
      giveBackText: `Sniffは、単なるエアドロップ発見ツールではありません。それは、現実世界の変化を促進するための手段でもあります。$SNIFFの取引の一部は、信頼できる保護犬団体や殺処分ゼロシェルターに直接支援として送られます。

毎年、世界中で数百万匹の犬たちが無視され、虐待され、放棄されています。アメリカでは330万匹もの犬がシェルターに収容され、そのうち150万匹が収容所の過密状態と資源不足のために安楽死しています。日本でも、毎年5万匹以上の犬が放棄され、その多くがパピーミルという劣悪な繁殖施設で虐待され、栄養失調や健康問題に苦しんでいます。

Sniffは、世界中の信頼できる団体（例えば、ヒューメイン・ソサエティや動物愛護団体など）と提携し、過剰繁殖、放棄、パピーミル問題に取り組んでいます。更には、犬肉文化に反対する活動も行っており、これに対しての啓蒙活動や法的支援を行っています。

これらの支援活動に、$SNIFFの使用を通じて貢献できます。トークン取引の一部は、去勢・避妊プログラムや犬の保護施設への寄付に使われるだけでなく、災害対応チームや動物福祉法の強化のためのロビー活動にも活用されます。実際、$SNIFFを使用することで、Web3を探索しながら、現実の動物保護活動に対する具体的な貢献が可能となります。

さらに、$SNIFFを使うことで社会貢献が増すことが確認されています。$SNIFFを使うたびに、現実世界で犬たちにとってより良い未来を作るための投資となります。例えば、毎月$SNIFFを使うユーザー1,000人あたり、少なくとも50匹の犬が新しい家に迎えられることが目標です。

$SNIFFを使うことで、あなたはWeb3を探索しながら現実世界の動物保護活動に貢献し、道徳的な報酬も手に入れることができます。あなたの1回の取引が、犬たちの命を救い、より良い未来を提供することにつながります。今すぐ$SNIFFを使用して、あなたの影響力を拡大し、社会的にも大きな変化をもたらしましょう。`,
      roadmap: 'ロードマップ',
      roadmapItems: [
        "2025年Q2：SniffスコアMVP公開＆初回寄付の実施",
        "2025年Q3：Sniffダッシュボード、NFTバッジシステム、DAO投票システムの統合",
        "2025年Q4：Sniff API公開、マルチチェーン対応、RescueChain（資金分配レイヤー）のベータ版リリース",
        "2026年Q1：SniffNetアルファリリース — カスタムAIスニファーエージェントの作成と訓練、可視化された挙動の提供",
        "2026年Q2：SniffCare公開 — ウェアラブル犬の感情・好み通訳システムの提供",
        "2026年Q4：Sniff憲法の公開 — 世界的な犬の福祉のための倫理的枠組み",
        "2027年Q1：SniffNationベータ開始 — 分散型犬市民権システムとインセンティブ経済の開始",
        "2027年後半：自律型AI嗅覚犬権利プロトコルに向けたグローバルインフラの拡大",
        "未来：すべての犬がデジタルで尊厳と権限を持つ存在として認識される"
      ],
      recentSniffs: '最近のSniffs / サービスハイライト',
      demoSniffs: [
        {
          name: '地域の保護団体をサポート',
          type: 'コミュニティの影響',
          requirements: '地域の犬の保護団体やシェルターとの提携。',
          description: 'Sniffは、地域の小規模な犬の保護団体と直接連携しています。これらの団体への支援により、$SNIFFの取引の一部が実際の動物福祉活動に活用され、資金が不足しているシェルターを支援します。'
        },
        {
          name: '犬福祉への継続的な寄付',
          type: '動物福祉',
          requirements: '殺処分ゼロシェルターや犬のリハビリテーション施設への寄付。',
          description: 'いくつかの殺処分ゼロシェルターや犬のリハビリテーションプログラムに寄付を行いました。これらの寄付は、保護された犬に医療支援を提供し、安全な生活環境を提供するために使用されます。'
        },
        {
          name: 'ボランティアと保護活動への支援',
          type: 'ボランティア活動',
          requirements: '保護された犬を支援するためのボランティア活動に参加。',
          description: 'Sniffは、保護された犬がより良い家庭に迎えられるよう支援するためのボランティアプログラムもサポートしています。これらのプログラムでは、犬のトレーニングや新しい飼い主に向けた教育資料を提供しています。'
        }
      ]      
    }
  };

  const t = translations[lang];

  return (
    <main className="bg-gradient-to-br from-zinc-950 to-zinc-900 text-white min-h-screen px-6 py-10 font-sans">
      <div className="text-right mb-4">
        <button onClick={() => setLang(lang === 'en' ? 'ja' : 'en')} className="text-sm text-orange-400 hover:underline">
          {t.toggle}
        </button>
      </div>

      <section className="text-center max-w-4xl mx-auto py-20">
        <img src="/hero-sniff.png" alt="Sniff AI Dog" className="mx-auto mb-8 w-48 h-48 rounded-full shadow-lg border border-orange-500 object-cover" />
        <motion.h1 initial={{ opacity: 0, y: -20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.8 }} className="text-5xl font-extrabold text-orange-400 tracking-tight">
          {t.title}
        </motion.h1>
        <p className="text-xl text-zinc-300 mt-6 leading-relaxed">{t.subtitle}</p>
        <a href="#sniffs" className="inline-block mt-8 px-8 py-4 bg-orange-500 hover:bg-orange-600 rounded-full text-white text-lg font-semibold shadow-lg transition-all">
          {t.cta}
        </a>
      </section>

      {[['why', 'whyText'], ['how', 'howText'], ['utility', 'utilityList'], ['giveBack', 'giveBackText'], ['roadmap', 'roadmapItems']].map(([headingKey, contentKey], i) => (
        <section key={headingKey} className="mt-20 max-w-4xl mx-auto px-4">
          <h2 className="text-3xl font-bold text-orange-300 mb-4 border-b border-orange-400 pb-2">{t[headingKey]}</h2>
          {Array.isArray(t[contentKey]) ? (
            <ul className="list-disc pl-6 text-zinc-300 space-y-2">
              {t[contentKey].map((item, idx) => <li key={idx}>{item}</li>)}
            </ul>
          ) : (
            <p className="text-zinc-300 whitespace-pre-line leading-relaxed">{t[contentKey]}</p>
          )}
        </section>
      ))}

<section id="sniffs" className="mt-20 max-w-4xl mx-auto">
  <h2 className="text-3xl font-bold text-orange-300 mb-6 border-b border-orange-400 pb-2">{t.recentSniffs}</h2>
  <div className="grid gap-8 md:grid-cols-3 sm:grid-cols-1">
    {t.demoSniffs.map((s, i) => (
      <motion.div key={i} className="bg-zinc-800 p-6 rounded-2xl shadow-lg hover:shadow-orange-400 transition-all border border-zinc-700" initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.2 }}>
        <h3 className="text-xl font-bold text-white mb-1">{s.name} <span className="text-sm text-zinc-400">({s.type})</span></h3>
        <p className="text-sm text-zinc-400">{s.requirements}</p>
        <p className="text-zinc-100 text-sm mt-1">{s.description}</p>
      </motion.div>
    ))}
  </div>
</section>

      <footer className="text-center mt-32 text-zinc-500 text-sm border-t border-zinc-700 pt-8">
        <p>{t.footer}</p>
      </footer>
    </main>
  );
}
