import React from 'react';
import { useState } from 'react';
import { motion } from 'framer-motion';
import './index.css';

export default function App() {
  const [lang, setLang] = useState('en');

  const translations = {
    en: {
      title: 'Sniff – The AI Dog Sniffing Out Airdrops and Injustice',
      subtitle: 'Sniff is your AI-powered watchdog – hunting valuable airdrops and challenging real-world cruelty.',
      cta: '🚀 Explore the Sniff Mission',
      footer: 'Built by humans. Powered by dogs. Driven by justice. © 2025 Sniff Protocol',
      toggle: '日本語へ',
      requirements: 'Requirements',
      why: 'Why Sniff?',
      whyText: `Sniff isn’t just another crypto analytics tool—it’s your unfair advantage in the airdrop race.

      In Web3, information overload is constant. Every day brings a new project, a new promise, a new buzz. But most of them are noise. Scammy Discord servers, fake Twitter hype, paid influencers—all manipulating attention. By the time the masses catch on, the real opportunities are long gone.
      
      Sniff is different. It’s your personal watchdog—a decentralized AI system trained to sniff out airdrops before they surface. We deploy multiple AI agents, each with deep domain expertise:
      - NLP models read the tone of announcements and developer updates
      - Smart contract evaluators flag honeypots and flawed tokenomics
      - Social signal agents detect inorganic virality and bot-driven campaigns
      - Memory agents remember past scams, rug pulls, and pump patterns
      
      What you get is not a list of projects. You get intelligence. Curated, explainable airdrop leads scored and filtered to match your risk profile and preferences. It’s discovery without distraction. Efficiency without compromise.
      
      Sniff isn’t chasing influencers or alpha groups—it’s building a machine that finds what others miss. We don’t wait for hype to validate a project. We analyze, score, and sniff before the crowd even hears a bark.
      
      But there’s more. Every sniff you follow also fights injustice. A fixed percentage of the protocol’s revenue goes directly to real-world animal rescue programs. In regions where dogs are abused, abandoned, or euthanized in secret, Sniff brings visibility, funding, and action. We partner with transparent organizations in Japan, the U.S., Southeast Asia, and beyond to create systemic change.
      
      In a world where profit usually comes at the expense of ethics, Sniff proves you can win both ways. Sniff is the first airdrop protocol that’s not just optimized for financial alpha—but for moral alpha too.
      
      It’s time to replace noise with trust. Replace hype with detection. Replace apathy with impact.
      
      Built by humans. Powered by dogs. Trained to sniff opportunity—and injustice.
      
      Sniff is not a meme — it’s a movement.

      $SniffAI was launched to make belief visible.  
      We wanted to see who truly resonated with our mission:  
      A project for dog lovers, by dog lovers, backed by real digital value.
      
      That’s why we built two tokens:

      $SniffAI (on Solana):  
      A trust test. No utility. No governance. Just belief.

      $SniffAI Protocol (on Virtual Protocol):  
      The main token.  
      Designed for long-term utility, governance, supply transparency, and participation in Sniff’s vision.

      $SniffAI Protocol is how we build forward — together.
      `,
      how: 'How Sniff Score Works',
      howText: `The Sniff Score is not just a number. It’s a dynamic, explainable signal generated by a decentralized ensemble of AI agents—each trained in a specific analytical domain—to detect, evaluate, and prioritize airdrop-worthy Web3 projects before the crowd.

Sniff’s architecture is modeled after multi-agent systems used in swarm robotics and adversarial inference environments. Each agent operates independently with its own model, data set, and evaluation heuristics. Their insights are then federated via a trust-weighted voting system, producing a final Sniff Score.

■ NLP Agents (Natural Language Processing)
These agents process whitepapers, dev updates, social media posts, and community messages. They assess semantic tone, rhetorical consistency, presence of evasive or promotional language, and similarity to historical scam signatures. They detect red flags like vague roadmaps, excessive future promises, or sudden pivot language.

■ Smart Contract Evaluators
Sniff scans token contracts for structural and behavioral risks: developer wallet concentration, mint/burn functions, ownership transfer logic, honeypot conditions, and time-locked functions. It incorporates static analysis tools like Slither and Mythril, combined with Sniff’s proprietary “Ethical Function Score” (EFS), to measure on-chain integrity.

■ Social Signal Detectors
These agents analyze account age distribution, engagement velocity, hashtag dynamics, influencer overlap, and known bot cluster traces. Using Sniff’s “Pattern Injection Score,” they assess how closely a project’s growth mirrors prior inorganic campaigns—measuring not popularity, but authenticity.

■ Memory Agents
Sniff’s memory subsystem records every past evaluation, tracking the long-term accuracy and volatility of each agent. These histories feed into Dynamic Agent Weighting—an adaptive feedback loop that reduces reliance on underperforming signals and boosts agents with proven precision.

All agents vote on a normalized score between 0–10, with weights adjusted via temporal trust coefficients. The final Sniff Score isn’t static—it reflects continuous updates from real-time data, agent performance, and evolving threat models.

Sniff doesn’t just tell you “what’s hot”—it explains why. It gives you actionable intelligence, not just alerts. Every score is backed by transparent, component-wise rationales that experienced traders and researchers can audit.

This isn’t sentiment analysis. It’s infrastructure-grade AI vigilance—built to scale, built to detect, built to be trusted.

Sniff Score: because in Web3, trust isn't given. It's sniffed out.`,
      utility: 'What $SNIFF Token Does',
      utilityList: [
        "Unlocks personalized airdrop dashboards, real-time cross-chain sniff alerts, and scoring insights powered by decentralized multi-agent AI.",
        "No-code interface to train your own custom AI agent—tailored for specific domains (DeFi, Memecoin, NFT) or scam-immune behavior patterns.",
        "Vote on sniff target priorities, agent upgrades, funding for dog rescue partners, and protocol ethics via SniffDAO.",
        "Your $SNIFF activity affects your SniffRank, which adjusts UI personalization strength, alpha access, and leaderboard placement.",
        "Earn NFT badges, agent beta access, and participation incentives for usage, feedback, and ethical contribution.",
        "A portion of fees is programmatically routed to trusted global dog protection NGOs—fully transparent and auditable on-chain."
      ],      
      giveBack: 'Give Back to Real Dogs',
      giveBackText: `Sniff isn’t just a tool for sniffing airdrops—it’s an instrument of change in the real world. A portion of every $SNIFF transaction directly supports animal welfare through verified dog rescue and no-kill shelters. 

Every year, millions of dogs worldwide face neglect, abuse, and abandonment. According to recent statistics, an estimated 3.3 million dogs enter U.S. shelters alone, with over 1.5 million euthanized due to overcrowding and lack of resources. In Japan, over 50,000 dogs are abandoned annually, and an alarming number of them are subjected to the horrors of puppy mills, where they face abuse and malnutrition.

Sniff partners with trusted organizations across the globe, including rescues like the Humane Society, to directly address issues like overbreeding, abandonment, puppy mills, and the inhumane dog meat trade still prevalent in certain parts of the world. By using $SNIFF, you aren’t just discovering high-value Web3 projects—you’re contributing to a better world for dogs who need it the most. 

Through the Sniff Protocol, we create a direct impact by ensuring that a portion of every token transaction goes towards animal rescue efforts. Whether it’s funding spay/neuter programs, supporting disaster response teams, or lobbying for stricter animal welfare laws, Sniff allows you to contribute while you explore and profit from Web3. Your participation brings both financial and moral reward, creating a legacy of ethical wealth-building in the blockchain space.

The more $SNIFF you use, the more impact you create. Every transaction, every vote, and every dollar spent is an investment in a better future for dogs in need. With Sniff, you can actively fight the injustices of the world while enjoying the benefits of decentralized finance—and know that your actions are creating real-world change, one sniff at a time.`,
      roadmap: 'Roadmap',
      tech: 'Technical Foundations',
      techText: `Sniff is powered by a real-time, decentralized multi-agent AI architecture. Each airdrop is independently analyzed by specialized AI agents—large language models (LLMs) for semantic analysis, on-chain graph analytics engines for token behavior, anomaly detection models for social metrics, and reputation-based memory subsystems. These agents use federated voting with weighted trust scores to generate a robust, interpretable Sniff Score.

Our AI stack runs on serverless edge infrastructure, optimizing for latency and verifiability. Developers can plug in new agents, deploy local fine-tuned models, or access aggregated scoring through our open API. The system is designed for transparency, auditability, and long-term adaptability to adversarial crypto dynamics.`,
      value: 'Why It Matters',
      valueText: `Crypto moves fast. Scams move faster. New users and even seasoned holders often fall prey to hyped projects with no substance. Sniff is your intelligent guard dog—cutting through the noise, surfacing ethical projects, and redistributing value to where it matters: real-world impact and justice.

$SNIFF is more than just a meme token. It's a utility layer for discovery, decision-making, and decentralized enforcement of ethics in Web3.`,
roadmapItems: [
  "Q2 2025: Launch Sniff Score MVP and initiate first real-world donations",
  "Q3 2025: Integrate public Sniff dashboards, NFT badge system, and DAO-based project voting",
  "Q4 2025: Release Sniff API, support multichain sniffing, and beta launch of RescueChain (fund distribution layer)",
  "Q1 2026: Alpha release of SniffNet — create/train custom AI sniff agents with visualized behavior",
  "Q2 2026: Launch SniffCare — wearable-integrated dog emotion and preference interpreter",
  "Q4 2026: Publish the SniffConstitution — global ethical framework for canine welfare",
  "Q1 2027: Begin SniffNation beta — decentralized canine citizenship and incentive economy",
  "Late 2027+: Expand global infrastructure toward autonomous AI-sniffed dog-rights protocol",
  "Future: Every dog is recognized as a sovereign being with digital dignity and agency"
],
recentSniffs: 'Recent Sniffs / Service Highlights',
demoSniffs: [
  {
    name: 'Supporting Local Rescue Organizations',
    type: 'Community Impact',
    requirements: 'Partnerships with local dog rescue groups and shelters.',
    description: 'Sniff is working directly with small, local organizations to support dog rescue missions. These partnerships help ensure that a portion of every $SNIFF token transaction goes towards real-life animal welfare, supporting shelters that are often underfunded.'
  },
  {
    name: 'Ongoing Donations for Dog Welfare',
    type: 'Animal Welfare',
    requirements: 'Contributions made to no-kill shelters and dog rehabilitation centers.',
    description: 'We have made initial donations to several no-kill shelters and dog rehabilitation programs. These ongoing efforts aim to provide rescue dogs with medical treatment and safe living spaces while they await adoption.'
  },
  {
    name: 'Volunteer and Rescue Support Activities',
    type: 'Volunteer Work',
    requirements: 'Participation in volunteer initiatives to help rescued dogs.',
    description: 'Sniff is also supporting volunteer programs that offer training for rescued dogs, helping them become more adoptable. These programs provide educational materials and resources for new dog owners, ensuring that rescued dogs have a loving home.'
  }
]


    },
    ja: {
      title: 'Sniff – エアドロと不正を嗅ぎ分けるAI犬',
      subtitle: 'SniffはAIで動く番犬です。価値あるエアドロップと、世界の不条理を嗅ぎつけます。',
      cta: '🚀 Sniffの使命を知る',
      footer: '人が作り、犬が嗅ぎ、正義が動く。© 2025 Sniff Protocol',
      toggle: 'English',
      requirements: '参加条件',
      why: 'なぜSniffなのか？',
      whyText: `Sniffは、ただの仮想通貨ツールではありません。エアドロップ競争を勝ち抜くために設計された、AIによる「先読み型の嗅覚システム」です。

今のWeb3は、毎日のようにプロジェクトが乱立し、次々とエアドロップ情報が流れてきます。しかし、それらの多くは“罠”です。Discordの招待リンク、謎のXキャンペーン、バイラル狙いの偽アカウント、そして資金を奪い逃げるラグプル。そんな世界で、本当に価値あるプロジェクトを、どうやって見抜くのか？

Sniffの答えは明確です。「犬のように、匂いで嗅ぎ分けろ。」

Sniffは、複数のAIエージェントによって構成されています。
・言語処理AIは、開発者の投稿やホワイトペーパーのトーンを解析
・スマートコントラクトアナライザーは、不正な挙動やトークン設計の矛盾を検出
・SNS解析エンジンは、ボット拡散や偽装バズをリアルタイムで監視
・記憶エージェントは、過去の詐欺・成功例を学習し、パターンマッチングで警告を発信

Sniffが提供するのは「リスト」ではなく「洞察」です。単なる情報ではなく、AIによって“本当に可能性があるエアドロップ”だけを、リスク別・テーマ別に整理して通知。あなたは判断だけに集中すればいい。ノイズも、作業も、フィルターも不要です。

Sniffは、誰かの発信やアルファグループに依存しません。Sniffは、誰よりも早く気づき、独自のロジックで“まだ誰も吠えていないチャンス”を発掘します。

さらにSniffの報酬モデルには、「現実世界での正義」が組み込まれています。プロトコルが得た収益の一部は、世界中の保護犬・殺処分ゼロ活動・災害救助・繁殖場問題への対策費として寄付されます。日本、アジア、欧米…地域ごとの団体と連携し、AIとWeb3の力で動物福祉の構造を変えていきます。

Sniffは、儲けと倫理を両立させた世界初のAIプロトコルです。
嗅ぎ当てるのは、チャンスだけではない。不正も、沈黙も、無関心さえも、Sniffは嗅ぎつける。

Web3は、嗅覚が試される時代に入りました。
Sniff——それは、吠える前に気づく、新しい正義の形です。

Sniffはただのミームではありません。  
これは「動き（ムーブメント）」です。

$SniffAIは、「誰が信じてくれるか」を可視化するために発行されました。  
犬を愛する人たちの手で、犬のために作る、**本物のデジタル価値を持ったプロジェクト**を信じてくれる人を探すために。

そのため、私たちは2つのトークンを用意しました。

$SniffAI（Solana上）  
信頼のテストです。ユーティリティも、ガバナンスもありません。あるのは「信じる力」だけ。

$SniffAI Protocol（Virtual Protocol上）  
本命トークンです。  
ユーティリティ・ガバナンス・供給の透明性・参加性を備えた、長期構築型の設計です。

このトークンこそが、Sniffの未来を一緒に築く基盤です。
`,

      how: 'Sniffスコアの仕組み',
      howText: `Sniffスコアは、単なる数値ではありません。これは、複数の専門AIエージェントが協調して生成する「動的かつ説明可能な信号」です。各エージェントは独自の専門領域で訓練されており、他の誰よりも早く、価値あるエアドロップ候補を特定・評価・優先順位付けするために機能します。

      Sniffのアーキテクチャは、群ロボティクスや敵対的推論環境で用いられるマルチエージェントシステムに着想を得ています。各エージェントは独自のモデル、データセット、評価アルゴリズムを持ち、独立して分析を行います。最終的なスコアは、信頼加重型のフェデレート投票によって統合されます。
      
      ■ NLPエージェント（自然言語処理）
      ホワイトペーパー、開発者のアップデート、SNS投稿、コミュニティメッセージなどを解析し、文脈のトーン、論理的一貫性、曖昧な表現や誇張的プロモーションの有無を評価します。また、過去の詐欺プロジェクトと類似する言語パターンも検出します。
      
      ■ スマートコントラクト評価エージェント
      開発者ウォレットの集中度、ミント/バーン機能、所有権移譲ロジック、ハニーポット構造、時間制限付き操作などを解析します。SlitherやMythrilなどの静的解析ツールに加え、Sniff独自の「倫理機能スコア（EFS）」によって、コードの健全性と透明性を総合評価します。
      
      ■ ソーシャルシグナル検出エージェント
      アカウントの年齢分布、エンゲージメント速度、ハッシュタグの拡散構造、インフルエンサーとの重複、既知のBotクラスタとの一致などを分析します。Sniff独自の「パターン注入スコア（Pattern Injection Score）」により、成長が本物か捏造かを見極めます。
      
      ■ メモリーエージェント
      各エージェントの過去の評価結果と実際のプロジェクト成果を記録し、長期的な精度・予測の安定性を学習します。この履歴は「動的エージェント重み付け（Dynamic Agent Weighting）」に反映され、信頼性の高いエージェントがより強く評価に寄与するよう適応します。
      
      すべてのエージェントは 0〜10 の正規化スコアに基づいて投票し、時系列的な信頼係数で重み付けされます。Sniffスコアは静的なものではなく、リアルタイムのデータ、モデル性能、脅威モデルの進化に応じて常に更新されます。
      
      Sniffは「何が流行っているか」を伝えるだけではありません。「なぜそう判断したか」まで説明します。出力されるスコアは、熟練トレーダーやリサーチャーが監査可能な、構成要素ごとの根拠を備えています。
      
      これは単なるセンチメント分析ではありません。これはインフラグレードのAI監視レイヤーです。スケール可能で、欺瞞に強く、信頼されるべき仕組み。
      
      Sniffスコア──Web3では信頼は与えられるものではない。嗅ぎ当てるものだ。`,
      
      utility: '$SNIFFトークンの機能',
      utilityList: [
        "パーソナライズされたエアドロップダッシュボード、クロスチェーン通知、AIスコアリング機能にアクセス可能。",
        "ノーコードで自分だけのAIスニファーを育成。DeFiやミームコイン特化型、詐欺耐性型など好みに最適化可能。",
        "Sniff対象の優先設定、エージェント改良、動物保護支援金の配分、倫理基準の更新などに投票可能。",
        "$SNIFFの使用行動がSniffRankに反映され、UIパーソナライズや早期機能アクセス、ランキングに影響。",
        "NFTバッジ、エージェントβアクセス、インセンティブ配布など、実際の活動に応じて報酬を獲得。",
        "収益の一部がスマートコントラクト経由で保護犬団体へ自動配分。全トランザクションは透明に記録。"
      ],
      giveBack: '犬たちへの還元',
      giveBackText: `Sniffは、単なるエアドロップ発見ツールではありません。それは、現実世界の変化を促進するための手段でもあります。$SNIFFの取引の一部は、信頼できる保護犬団体や殺処分ゼロシェルターに直接支援として送られます。

毎年、世界中で数百万匹の犬たちが無視され、虐待され、放棄されています。アメリカでは330万匹もの犬がシェルターに収容され、そのうち150万匹が収容所の過密状態と資源不足のために安楽死しています。日本でも、毎年5万匹以上の犬が放棄され、その多くがパピーミルという劣悪な繁殖施設で虐待され、栄養失調や健康問題に苦しんでいます。

Sniffは、世界中の信頼できる団体（例えば、ヒューメイン・ソサエティや動物愛護団体など）と提携し、過剰繁殖、放棄、パピーミル問題に取り組んでいます。更には、犬肉文化に反対する活動も行っており、これに対しての啓蒙活動や法的支援を行っています。

これらの支援活動に、$SNIFFの使用を通じて貢献できます。トークン取引の一部は、去勢・避妊プログラムや犬の保護施設への寄付に使われるだけでなく、災害対応チームや動物福祉法の強化のためのロビー活動にも活用されます。実際、$SNIFFを使用することで、Web3を探索しながら、現実の動物保護活動に対する具体的な貢献が可能となります。

さらに、$SNIFFを使うことで社会貢献が増すことが確認されています。$SNIFFを使うたびに、現実世界で犬たちにとってより良い未来を作るための投資となります。例えば、毎月$SNIFFを使うユーザー1,000人あたり、少なくとも50匹の犬が新しい家に迎えられることが目標です。

$SNIFFを使うことで、あなたはWeb3を探索しながら現実世界の動物保護活動に貢献し、道徳的な報酬も手に入れることができます。あなたの1回の取引が、犬たちの命を救い、より良い未来を提供することにつながります。今すぐ$SNIFFを使用して、あなたの影響力を拡大し、社会的にも大きな変化をもたらしましょう。`,
      roadmap: 'ロードマップ',
      roadmapItems: [
        "2025年Q2：SniffスコアMVP公開＆初回寄付の実施",
        "2025年Q3：Sniffダッシュボード、NFTバッジシステム、DAO投票システムの統合",
        "2025年Q4：Sniff API公開、マルチチェーン対応、RescueChain（資金分配レイヤー）のベータ版リリース",
        "2026年Q1：SniffNetアルファリリース — カスタムAIスニファーエージェントの作成と訓練、可視化された挙動の提供",
        "2026年Q2：SniffCare公開 — ウェアラブル犬の感情・好み通訳システムの提供",
        "2026年Q4：Sniff憲法の公開 — 世界的な犬の福祉のための倫理的枠組み",
        "2027年Q1：SniffNationベータ開始 — 分散型犬市民権システムとインセンティブ経済の開始",
        "2027年後半：自律型AI嗅覚犬権利プロトコルに向けたグローバルインフラの拡大",
        "未来：すべての犬がデジタルで尊厳と権限を持つ存在として認識される"
      ],
      recentSniffs: '最近のSniffs / サービスハイライト',
      demoSniffs: [
        {
          name: '地域の保護団体をサポート',
          type: 'コミュニティの影響',
          requirements: '地域の犬の保護団体やシェルターとの提携。',
          description: 'Sniffは、地域の小規模な犬の保護団体と直接連携しています。これらの団体への支援により、$SNIFFの取引の一部が実際の動物福祉活動に活用され、資金が不足しているシェルターを支援します。'
        },
        {
          name: '犬福祉への継続的な寄付',
          type: '動物福祉',
          requirements: '殺処分ゼロシェルターや犬のリハビリテーション施設への寄付。',
          description: 'いくつかの殺処分ゼロシェルターや犬のリハビリテーションプログラムに寄付を行いました。これらの寄付は、保護された犬に医療支援を提供し、安全な生活環境を提供するために使用されます。'
        },
        {
          name: 'ボランティアと保護活動への支援',
          type: 'ボランティア活動',
          requirements: '保護された犬を支援するためのボランティア活動に参加。',
          description: 'Sniffは、保護された犬がより良い家庭に迎えられるよう支援するためのボランティアプログラムもサポートしています。これらのプログラムでは、犬のトレーニングや新しい飼い主に向けた教育資料を提供しています。'
        }
      ]      
    },
    zh: {
      title: 'Sniff – AI 狗狗侦测空投与不公',
      subtitle: 'Sniff 是你的 AI 守护犬 – 寻找有价值的空投，挑战现实世界的残酷。',
      cta: '🚀 探索 Sniff 使命',
      footer: '由人类打造。由狗狗驱动。以正义为导向。© 2025 Sniff 协议',
      toggle: '切换到日语',
      requirements: '需求条件',
      why: '为什么选择 Sniff？',
      whyText: `Sniff 不只是另一个加密分析工具——它是你在空投竞赛中的不公平优势。
    
    在 Web3 世界中，信息超载是常态。每天都有新项目、新承诺、新炒作。但其中大多数都是噪音：虚假的 Discord 群、虚构的 Twitter 热点、付费网红——这些都在操纵注意力。当大众反应过来时，真正的机会早已溜走。
    
    Sniff 不一样。它是你的私人守护犬——一个去中心化的 AI 系统，专为在空投出现前嗅出其踪迹而训练。我们部署了多个具有深度领域专业知识的 AI 代理：
    - NLP 模型分析公告和开发者更新的语气
    - 智能合约分析器识别蜜罐和有缺陷的代币模型
    - 社交信号代理检测无机炒作和机器人驱动的营销
    - 记忆代理记录过去的骗局、拉盘和套路模式
    
    你得到的不只是项目清单，而是情报。经过筛选并可解释的空投线索，按你的风险偏好和兴趣进行评分过滤。这是一种不分心的发现方式，兼顾效率和判断力。
    
    Sniff 不追随网红或 alpha 群组——它构建的是一台能够发现其他人遗漏信息的机器。我们不等炒作验证项目，而是抢在任何叫声出现之前进行分析、评分和嗅探。
    
    更重要的是：你跟随的每一次嗅探，也是在对抗不公。协议收入的一部分将直接捐赠给现实中的动物救助项目。在狗狗被虐待、遗弃或秘密安乐死的地区，Sniff 提供曝光、资金和行动。我们与日本、美国、东南亚等地区的透明组织合作，推动系统性改变。
    
    在这个利润往往以道德为代价的世界里，Sniff 证明你可以双赢——既获取财务 alpha，也获取道德 alpha。
    
    是时候用信任替代噪音，用侦测替代炒作，用影响替代冷漠了。
    
    由人类打造。由狗狗驱动。训练来嗅出机会与不公。

    Sniff不是一个meme，它是一场行动。

$SniffAI的推出，是为了让信念可见。  
我们想知道，谁真正认同我们的使命：  
一个由爱狗者发起、为爱狗者服务的项目，背后有真正数字价值支撑。

因此我们设计了两个代币：

$SniffAI（在 Solana 上）  
这是一次信任测试。没有功能、没有治理，只有信仰。

$SniffAI Protocol（在 Virtual Protocol 上）  
这是主代币。  
具备长期使用性、治理机制、透明供应与参与机会，全面支持Sniff愿景的建设。

SniffAI Protocol，就是我们一起走向未来的方式。
    `,
      how: 'Sniff Score 是如何工作的？',
      howText: `Sniff Score 不是一个简单的数字。它是由去中心化 AI 多代理系统动态生成的可解释信号，专为在大众发现之前侦测、评估并优先排序优质空投项目。
    
    Sniff 的架构借鉴了群体机器人系统与对抗性推理环境中的多代理模型。每个代理独立运行，拥有自己的模型、数据集和评估逻辑。其洞察结果经由加权信任投票系统联邦整合，生成最终的 Sniff Score。
    
    ■ NLP 代理（自然语言处理）
    这些代理解析白皮书、开发日志、社交媒体和社区讨论，评估语义语气、一致性、回避/营销语言，以及是否与历史骗局相似。能识别模糊路线图、过度承诺、突然转向等风险信号。
    
    ■ 智能合约分析器
    扫描代币合约中的结构和行为风险：开发者持仓集中、铸币/销毁函数、权限转移逻辑、蜜罐设置、时间锁等。结合静态分析工具如 Slither 与 Mythril，以及专属“道德函数评分”（EFS）来评估链上可信度。
    
    ■ 社交信号检测器
    分析账号年龄分布、互动速度、标签动态、网红交叉覆盖与机器人网络。基于“模式注入评分”衡量是否存在异常传播与假热度。
    
    ■ 记忆代理
    记录每次评估结果，并追踪代理的历史准确率与稳定性。该记录用于动态代理权重机制（Dynamic Agent Weighting），自动调整各代理影响力，提升整体精度。
    
    所有代理在 0–10 分之间投票，权重依时序信任系数调整。最终 Sniff Score 实时更新，反映数据、性能与威胁演化。
    
    Sniff 不只是告诉你“什么项目热门”，而是解释“为什么”。每一个评分都有组件级解释，供交易者与研究者审核。
    
    这不仅是情绪分析——是基础设施级 AI 警觉系统，具备可扩展性、检测力与可信性。
    
    Sniff Score：在 Web3 中，信任不是给予的——而是嗅出来的。`,
      utility: '$SNIFF 的作用',
      utilityList: [
        "解锁个性化空投仪表板、跨链实时嗅探提醒、AI 评分详情。",
        "通过零代码界面训练你的专属 AI 代理（支持 DeFi、Memecoin、NFT 或防诈骗行为模式）。",
        "通过 SniffDAO 投票决定嗅探目标优先级、代理升级、动物救助基金与道德协议。",
        "你的 $SNIFF 活动影响 SniffRank，进一步影响个性化强度、信息优先权限与排行榜。",
        "通过使用、反馈与道德贡献，可获得 NFT 徽章、测试权限与奖励。",
        "每笔交易的一部分收入自动转入全球可信动物保护组织，全链上可审计。"
      ],
      giveBack: '回馈真正的狗狗',
      giveBackText: `Sniff 不只是一个空投嗅探工具——它也是现实世界变革的驱动者。每笔 $SNIFF 交易的一部分都会支持经过验证的动物福利组织和无杀庇护所。 
    
    每年，全球有数百万只狗遭受忽视、虐待和遗弃。仅美国就有约 330 万只狗进入收容所，其中超 150 万只被安乐死。在日本，每年有超过 5 万只狗被遗弃，许多仍被困于残忍的繁殖场，面临虐待和营养不良。
    
    Sniff 与全球信赖的组织合作，如 Humane Society，直面过度繁殖、弃养、黑心狗场与犬肉交易等问题。使用 $SNIFF，你不仅在发现有价值的 Web3 项目，更在为最需要帮助的狗狗创造更美好的世界。
    
    通过 Sniff 协议，我们确保每笔交易的一部分都用于动物救助：资助绝育计划、支持灾难响应团队、推动动物保护立法改革。
    
    你使用得越多，影响就越大。每一次交易、投票和参与，都是为狗狗们的未来投资。
    
    Sniff 让你在享受去中心化金融的同时，也能主动抗击不公，让每一次嗅探都改变现实。`,
      roadmap: '路线图',
      tech: '技术基础',
      techText: `Sniff 由实时、去中心化的多代理 AI 架构驱动。每个空投项目由专用 AI 代理独立分析：大型语言模型（LLM）处理语义分析，链上图分析引擎检测代币行为，异常检测模型监控社交指标，以及基于声誉的记忆子系统追踪历史行为。
    
    这些代理通过加权信任投票系统进行整合，生成稳健、可解释的 Sniff Score。
    
    AI 栈运行在无服务器的边缘计算架构上，优化延迟和可验证性。开发者可插入新代理，部署本地微调模型，或通过开放 API 获取聚合评分。
    
    整个系统以透明、可审计、可长期适应对抗性加密环境为设计核心。`,
      value: '为什么这很重要？',
      valueText: `加密发展迅速，骗局更快。无论新用户还是老手，常被炒作项目所欺骗。
    
    Sniff 就是你的智能警犬——清除噪音、发掘有道德的项目，并将价值重分配到有意义的地方：现实中的影响与正义。
    
    $SNIFF 不只是一个 meme 代币。它是一个在 Web3 中实现发现、判断与道德执行的实用层。`,
      roadmapItems: [
        "2025 Q2：发布 Sniff Score MVP，启动首次动物救助捐赠",
        "2025 Q3：整合公开仪表板、NFT 徽章系统与 DAO 项目投票",
        "2025 Q4：发布 Sniff API，支持多链嗅探，测试 RescueChain（资金分发层）",
        "2026 Q1：发布 SniffNet Alpha——创建/训练自定义 AI 嗅探代理并可视化行为",
        "2026 Q2：上线 SniffCare——集成穿戴设备，解读狗狗情绪与偏好",
        "2026 Q4：发布《Sniff 宪章》——全球犬类伦理框架",
        "2027 Q1：启动 SniffNation 测试——去中心化犬类公民与激励经济",
        "2027 年末及以后：扩大全球基础设施，构建自治 AI 嗅探犬权协议",
        "未来：每只狗都被视为拥有数字尊严与自主权的主权存在"
      ],
      recentSniffs: '最新嗅探 / 服务亮点',
      demoSniffs: [
        {
          name: '支持本地救助组织',
          type: '社区影响',
          requirements: '与本地狗狗救助机构与收容所建立合作。',
          description: 'Sniff 正在与小型本地机构直接合作，支持救助行动。每笔 $SNIFF 交易的一部分将用于支持这些资金紧张的收容所。'
        },
        {
          name: '持续性捐赠以支持狗狗福利',
          type: '动物福利',
          requirements: '对无杀收容所与康复中心的资金支持。',
          description: '我们已向多个无杀狗狗庇护所与康复中心进行了初始捐赠，致力于为被救助的狗提供医疗照护与安全环境，直到它们被领养。'
        },
        {
          name: '志愿者与救援支援活动',
          type: '志愿服务',
          requirements: '参与志愿活动，协助被救助狗狗。',
          description: 'Sniff 也支持训练救助狗狗的志愿者计划，帮助提升其被收养机会，同时提供狗主教学与资源，让救助狗狗拥有真正的家。'
        }
      ]
    },    
    ko: {
      title: 'Sniff – 에어드롭과 부조리를 추적하는 AI 강아지',
      subtitle: 'Sniff는 당신의 AI 감시견입니다 – 가치 있는 에어드롭을 찾고 현실의 부조리에 맞섭니다.',
      cta: '🚀 Sniff 미션 살펴보기',
      footer: '사람이 만들고, 강아지가 구동하며, 정의로 이끕니다. © 2025 Sniff 프로토콜',
      toggle: '일본어로 전환',
      requirements: '요구 사항',
      why: '왜 Sniff인가?',
      whyText: `Sniff는 또 하나의 크립토 분석 툴이 아닙니다—에어드롭 경쟁에서 당신만의 불공정한 이점을 제공합니다.
    
    Web3에서는 정보 과잉이 일상입니다. 매일 새로운 프로젝트, 새로운 약속, 새로운 유행이 등장합니다. 그러나 대부분은 소음입니다. 사기성 디스코드, 가짜 트위터 열풍, 유료 인플루언서—모두 주의를 조작합니다. 대중이 깨달았을 땐 이미 기회는 사라진 뒤입니다.
    
    Sniff는 다릅니다. 개인 AI 감시견입니다—공개되기 전에 에어드롭을 포착하도록 훈련된 분산형 AI 시스템입니다. Sniff는 다양한 전문 AI 에이전트를 배치합니다:
    - NLP 모델이 개발 업데이트 및 공지의 어조 분석
    - 스마트 계약 분석기가 허니팟 및 구조적 위험 탐지
    - 소셜 시그널 분석기가 봇 활동과 비정상 유행 감지
    - 메모리 에이전트가 과거 사기 및 펌핑 패턴 기록
    
    Sniff는 단순한 프로젝트 목록이 아니라, 당신에게 맞춘 분석 정보를 제공합니다. 선별되고 설명 가능한 에어드롭 후보를 리스크 성향에 따라 점수화하고 필터링합니다. 산만함 없이 발견하고, 타협 없는 효율성을 제공합니다.
    
    Sniff는 인플루언서나 알파 그룹을 쫓지 않습니다—대중이 모르고 지나치는 것을 발견하는 기계를 구축합니다. 유행이 형성되기 전, 분석하고 평가하며 추적합니다.
    
    더 나아가, 당신이 따르는 Sniff는 실제 세상의 부조리와도 맞섭니다. 프로토콜 수익의 일부는 전 세계 유기견 보호 및 구조 단체에 기부됩니다. 일본, 미국, 동남아 등에서 학대받거나 버려지는 개들을 돕기 위해 투명한 조직과 협력합니다.
    
    윤리를 희생하여 이익을 얻는 세상에서 Sniff는 두 가지 모두를 실현할 수 있음을 증명합니다. 재정적 알파와 도덕적 알파를 동시에 추구하세요.
    
    소음을 신뢰로, 유행을 탐지로, 무관심을 영향력으로 바꾸는 시간입니다.
    
    Sniff는 단순한 밈이 아닙니다.  
    그것은 하나의 '움직임'입니다.
    
    $SniffAI는 진정으로 믿어주는 사람이 누구인지 확인하기 위해 발행되었습니다.  
    강아지를 사랑하는 사람들이 직접 만들고, 진짜 디지털 가치를 바탕으로 하는 프로젝트에  
    공감해줄 사람을 찾기 위해서였습니다.
    
    그래서 우리는 두 개의 토큰을 만들었습니다.
    
    $SniffAI (Solana 기반)  
    신뢰 테스트입니다. 유틸리티도, 거버넌스도 없습니다.  
    있는 것은 ‘믿음’뿐입니다.
    
    $SniffAI Protocol (Virtual Protocol 기반)  
    이것이 본 토큰입니다.  
    장기적인 사용성, 거버넌스, 공급 투명성, 참여 기회를 갖춘 구조로 Sniff의 비전을 실현하기 위한 기반입니다.
    
    이 토큰이야말로 Sniff의 미래를 함께 만들어갈 핵심입니다.
    `,
      how: 'Sniff 점수는 어떻게 작동하나요?',
      howText: `Sniff 점수는 단순한 숫자가 아닙니다. 분산형 AI 다중 에이전트 시스템이 생성하는 동적이며 설명 가능한 신호입니다.
    
    Sniff의 구조는 스웜 로보틱스와 적대적 추론 환경에서의 다중 에이전트 시스템을 기반으로 합니다. 각 에이전트는 독립적으로 작동하며, 고유 모델과 데이터셋, 평가 기준을 가집니다. 이들의 통찰은 신뢰 기반 가중 투표로 통합되어 최종 Sniff 점수를 생성합니다.
    
    ■ NLP 에이전트
    백서, 개발자 글, 소셜 미디어를 분석해 어조, 일관성, 회피적/선전성 언어 및 사기 유사 패턴을 감지합니다.
    
    ■ 스마트 계약 평가기
    토큰의 소유 구조, 민트/소각, 권한 이전, 허니팟, 타임락 등을 분석하여 구조적 위험을 평가합니다. Slither, Mythril 등과 자체 윤리 점수(EFS)를 사용합니다.
    
    ■ 소셜 시그널 감지기
    계정 생성일, 해시태그 확산, 인플루언서 중복, 봇 클러스터를 분석하여 인위적인 확산 여부를 판단합니다.
    
    ■ 메모리 에이전트
    과거 평가 데이터를 기록하고 정확도를 추적합니다. 이 기록은 성능 기반 가중치 조정에 사용됩니다.
    
    각 에이전트는 0~10 점으로 평가하고, 시간 기반 신뢰도에 따라 가중치가 조정됩니다. 결과는 실시간으로 업데이트되며, 위험 변화에도 적응합니다.
    
    Sniff는 “뜨는 것”만 말하지 않고, 그 이유도 설명합니다. 트레이더와 분석가가 감사할 수 있는 투명한 근거를 제공합니다.
    
    이건 단순한 감성 분석이 아닙니다. 인프라 수준의 AI 감시 시스템입니다.
    
    Web3에서 신뢰는 주어지는 것이 아닙니다—嗅ぎ分けられる 것입니다.`,
      utility: '$SNIFF 토큰의 역할',
      utilityList: [
        "개인 맞춤형 에어드롭 대시보드, 실시간 멀티체인 탐지 알림, AI 점수 데이터 해제",
        "DeFi, 밈코인, NFT 등 도메인별 커스텀 AI 에이전트를 코드 없이 직접 훈련",
        "SniffDAO를 통해 탐지 우선순위, 업그레이드, 구조 기금, 윤리 방침에 투표 참여",
        "$SNIFF 활동이 SniffRank에 반영되어 UI 개인화, 알파 접근 권한, 순위에 영향",
        "사용, 피드백, 윤리적 기여를 통해 NFT 뱃지, 에이전트 베타 접근 등 리워드 획득",
        "모든 수수료의 일부는 전 세계 반려견 구조 단체에 자동 기부 – 온체인 검증 가능"
      ],
      giveBack: '진짜 강아지들을 위한 기부',
      giveBackText: `Sniff는 에어드롭만 탐지하는 도구가 아닙니다—현실을 바꾸는 수단이기도 합니다. $SNIFF의 모든 거래 중 일부는 구조 단체와 보호소를 통해 직접 기부됩니다.
    
    미국에서는 매년 약 330만 마리의 개가 보호소로 보내지며, 150만 마리 이상이 안락사됩니다. 일본에서는 매년 5만 마리 이상이 유기되며, 그 중 일부는 강아지 공장에서 학대당합니다.
    
    Sniff는 Humane Society 등을 포함한 글로벌 단체와 협력하여 유기견 구조, 중성화 지원, 재난 대응, 강아지 고기 금지 입법 등에 기여합니다.
    
    $SNIFF를 사용할수록 더 많은 영향력을 발휘할 수 있습니다. 당신의 모든 거래와 활동은 재정적 수익뿐만 아니라 도덕적 기여로도 이어집니다.
    
    DeFi를 즐기면서 세상을 더 나은 곳으로 만들 수 있습니다. Sniff와 함께라면 가능합니다.`,
      roadmap: '로드맵',
      tech: '기술 기반',
      techText: `Sniff는 실시간, 분산형 다중 AI 에이전트 아키텍처 위에 구축되어 있습니다. 각 에이전트는 대형 언어 모델(LLM), 온체인 그래프 분석, 소셜 이상 탐지, 신뢰 기반 메모리 시스템 등 역할을 수행합니다.
    
    각 AI는 독립적으로 분석한 뒤, 신뢰 기반 가중 투표로 점수를 통합합니다.
    
    서버리스 엣지 인프라에서 실행되어 지연 없이 빠르게 반응하며, 개발자는 새로운 에이전트를 연결하거나 API를 통해 점수를 활용할 수 있습니다.
    
    모든 설계는 투명성, 감시 가능성, 그리고 변화하는 Web3 환경에 대한 적응력을 염두에 두고 만들어졌습니다.`,
      value: '왜 중요한가요?',
      valueText: `암호화폐는 빠르게 변하고, 사기는 그보다 빠릅니다. 많은 사용자들이 겉만 번지르르한 프로젝트에 당하고 있습니다.
    
    Sniff는 그런 혼란을 정리해주는 AI 감시견입니다. 도덕적 기준을 바탕으로 진짜 가치를 발굴하고, 현실에 영향력을 미칩니다.
    
    $SNIFF는 밈코인이 아닙니다. Web3에서의 윤리와 탐색, 판단을 위한 실질적인 유틸리티 계층입니다.`,
      roadmapItems: [
        "2025 Q2: Sniff Score MVP 출시, 첫 구조 기부 시작",
        "2025 Q3: 대시보드, NFT 뱃지, DAO 기반 투표 기능 통합",
        "2025 Q4: Sniff API 출시, 멀티체인 지원, RescueChain 베타",
        "2026 Q1: SniffNet 알파 – 커스텀 에이전트 생성 및 시각화 도구 제공",
        "2026 Q2: SniffCare 출시 – 강아지 감정/선호 해석 웨어러블 통합",
        "2026 Q4: Sniff 헌장 발표 – 글로벌 동물 윤리 기준 제정",
        "2027 Q1: SniffNation 베타 – 탈중앙화 강아지 시민권 경제 시작",
        "2027 후반~: 전 세계 인프라 확대 및 AI 기반 반려동물 권리 프로토콜 실현",
        "미래: 모든 개가 디지털 존엄과 자율권을 가진 존재로 인정받는 세계"
      ],
      recentSniffs: '최근 Sniff 하이라이트',
      demoSniffs: [
        {
          name: '지역 구조 단체 지원',
          type: '커뮤니티 영향',
          requirements: '지역 유기견 보호소와의 파트너십',
          description: 'Sniff는 지역의 소규모 단체들과 직접 협력하여 구조 임무를 지원합니다. $SNIFF 거래 일부는 자금난을 겪는 보호소로 전달됩니다.'
        },
        {
          name: '유기견 복지 기부 진행 중',
          type: '동물 복지',
          requirements: '안락사 금지 보호소와 재활 프로그램에 기여',
          description: 'Sniff는 복지 센터 및 보호소에 초기 기부를 완료했으며, 구조된 강아지에게 치료와 안전한 환경을 제공합니다.'
        },
        {
          name: '자원봉사 및 구조 지원 활동',
          type: '봉사 활동',
          requirements: '구조된 강아지를 돕는 자원봉사 프로그램 참여',
          description: 'Sniff는 구조견의 입양 가능성을 높이기 위한 훈련 프로그램과 새 주인을 위한 교육 리소스를 지원합니다.'
        }
      ]
    }    
  };

  const t = translations[lang];

  return (
    <main className="bg-gradient-to-br from-zinc-950 to-zinc-900 text-white min-h-screen px-6 py-10 font-sans">
    <div className="text-right mb-4 space-x-4">
      <button onClick={() => setLang('en')} className="text-sm text-orange-400 hover:underline">EN</button>
      <button onClick={() => setLang('ja')} className="text-sm text-orange-400 hover:underline">日本語</button>
      <button onClick={() => setLang('zh')} className="text-sm text-orange-400 hover:underline">中文</button>
      <button onClick={() => setLang('ko')} className="text-sm text-orange-400 hover:underline">한국어</button> 
    </div>


      <section className="text-center max-w-4xl mx-auto py-20">
        <img src="/hero-sniff.png" alt="Sniff AI Dog" className="mx-auto mb-8 w-48 h-48 rounded-full shadow-lg border border-orange-500 object-cover" />
        <motion.h1 initial={{ opacity: 0, y: -20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.8 }} className="text-5xl font-extrabold text-orange-400 tracking-tight">
          {t.title}
        </motion.h1>
        <p className="text-xl text-zinc-300 mt-6 leading-relaxed">{t.subtitle}</p>
        <a
          href="https://pump.fun/coin/AZQhrBRYXBNtLo97C6s2X4yFK2XDRCtwwVSVU9TJpump"
          target="_blank"
          rel="noopener noreferrer"
          className="inline-block mt-4 px-8 py-3 bg-green-500 hover:bg-green-600 rounded-full text-white text-base font-semibold shadow transition-all"
        >
          Buy $SNIFFAI Token
        </a>
        <a
          href="#mission"
          target="_blank"
          rel="noopener noreferrer"
          className="inline-block mt-4 px-8 py-3 bg-green-500 hover:bg-green-600 rounded-full text-white text-base font-semibold shadow transition-all"
        >
          Buy $SNIFFAI Protocol(comming soon)
        </a>
      </section>

      {[['why', 'whyText'], ['how', 'howText'], ['utility', 'utilityList'], ['giveBack', 'giveBackText'], ['roadmap', 'roadmapItems']].map(([headingKey, contentKey], i) => (
        <section id="mission" key={headingKey} className="mt-20 max-w-4xl mx-auto px-4">
          <h2 className="text-3xl font-bold text-orange-300 mb-4 border-b border-orange-400 pb-2">{t[headingKey]}</h2>
          {Array.isArray(t[contentKey]) ? (
            <ul className="list-disc pl-6 text-zinc-300 space-y-2">
              {t[contentKey].map((item, idx) => <li key={idx}>{item}</li>)}
            </ul>
          ) : (
            <p className="text-zinc-300 whitespace-pre-line leading-relaxed">{t[contentKey]}</p>
          )}
        </section>
      ))}

<section id="sniffs" className="mt-20 max-w-4xl mx-auto">
  <h2 className="text-3xl font-bold text-orange-300 mb-6 border-b border-orange-400 pb-2">{t.recentSniffs}</h2>
  <div className="grid gap-8 md:grid-cols-3 sm:grid-cols-1">
    {t.demoSniffs.map((s, i) => (
      <motion.div key={i} className="bg-zinc-800 p-6 rounded-2xl shadow-lg hover:shadow-orange-400 transition-all border border-zinc-700" initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.2 }}>
        <h3 className="text-xl font-bold text-white mb-1">{s.name} <span className="text-sm text-zinc-400">({s.type})</span></h3>
        <p className="text-sm text-zinc-400">{s.requirements}</p>
        <p className="text-zinc-100 text-sm mt-1">{s.description}</p>
      </motion.div>
    ))}
  </div>
</section>

      <footer className="text-center mt-32 text-zinc-500 text-sm border-t border-zinc-700 pt-8">
        <p>{t.footer}</p>
        <a
          href="https://x.com/SniffAIprotocol"
          target="_blank"
          rel="noopener noreferrer"
          className="inline-block mt-2 text-orange-400 hover:underline"
         >
        Follow us on X (formerly Twitter)
  </a>
      </footer>
    </main>
  );
}
